use_frameworks!

platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'MKBaseModuleLibrary_Example' do
  pod 'MKBaseModuleLibrary', :path => '../'

  target 'MKBaseModuleLibrary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
