use_frameworks!

platform :ios, '9.0'

target 'MKBaseModuleLibrary_Example' do
  pod 'MKBaseModuleLibrary', :path => '../'

  target 'MKBaseModuleLibrary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
